### ISSUE TITLE
getSSL fails on _new_ subdomain.

### ISSUE THREAD

**Issue by haroldiedema** [HielkeJ/puppet-hielkejletsencrypt#1]
Because we're using a 2 level deep sub domain, we can't use our existing wildcard certificate.
Enabling "use_ssl" works, except for the initial run when there is no certificate yet.

```yaml
  sub.domain.bouw7.nl:
    domain: 'sub.domain.bouw7.nl'
    websitebasedir: '/var/www/websites/domain'
    docroot: 'live/web'
    system_user: 'www-data'
    manageVhostDir: false
    use_ssl: 'letsencrypt'
```

The above config results in the following error when running the agent by hand:
```
Failed to call refresh: '/etc/ssl/letsencrypt/getssl -U -w /etc/ssl/letsencrypt/conf -q sub.domain.bouw7.nl' returned 1 instead of one of [0]
```

When running the above command manually, it still won't work, but when you add a trailing `/` after the conf directory, it works.

Consecutive puppet runs work fine after this.
